apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c4qtpagg6-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-4cae8d87e6.ncwm.p3.openshiftapps.com/rhtap/rhtap-qe:53fa7e6d115d139771e7b87af432a309635a4a26@sha256:64c7b65524fa4e533817732a14f886fc782d7c541b693d3bbf3c804c17c78fde
          name: container-image
