apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c4qtpagg6-python
  janus-idp.io/tekton: c4qtpagg6-python
  backstage.io/kubernetes-id: c4qtpagg6-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c4qtpagg6-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
